FROM ubuntu:18.04
RUN apt-get update && apt-get install -y wget libpcap0.8-dev libuv1-dev && wget https://github.com/spacemeowx2/switch-lan-play/releases/download/v0.2.1/lan-play-linux && chmod +x ./lan-play-linux
